-- MySQL Script generated by MySQL Workbench
-- Wed Jun 29 01:37:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema amistad3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema amistad3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `amistad3` ;
USE `mydb` ;
USE `amistad3` ;

-- -----------------------------------------------------
-- Table `amistad3`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amistad3`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amistad3`.`red_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amistad3`.`red_social` (
  `idPersona` INT NOT NULL,
  `idConocido` INT NOT NULL,
  PRIMARY KEY (`idPersona`, `idConocido`),
  INDEX `fk_Amistad_Persona1_idx` (`idConocido` ASC) VISIBLE,
  CONSTRAINT `fk_Amistad_Persona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `amistad3`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Amistad_Persona1`
    FOREIGN KEY (`idConocido`)
    REFERENCES `amistad3`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `amistad3`.`Gustos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `amistad3`.`Gustos` (
  `idPersona` INT NOT NULL,
  `peliculaFavorita` VARCHAR(45) NULL,
  `juegoFavorito` VARCHAR(45) NULL,
  `libroFavorito` VARCHAR(45) NULL,
  `deporteFavorito` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_Gustos_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `amistad3`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
